#!/bin/bash

VERSION=4.16.0

help() {
  echo "Usage:"
  echo "  zmicro package install code-server <args...>"
  echo ""
}

install() {
  curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=$VERSION
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  if [ "$?" != "0" ]; then
    log::error "failed to install code-server."
  else
    log::success "install code-server success."
  fi
}

run() {
  core $@
}

run $@
